syntax = "proto3";
package bifrost;

message InboundGradient {
    string node_id = 1;
    uint32 round_id = 2;
    repeated uint32 indices = 3;
    repeated float values = 4;
}

service OperationalHub {
    rpc StreamGradients (stream InboundGradient) returns (StreamResponse);
}

service GradientService{
  rpc StreamGradients (stream GradientPacket) returns (StreamResponse);
}

message GradientPacket {
  string node_id = 1;
  uint32 sequence_number = 2;
  repeated float gradient_chunk = 3;
}

message StreamResponse{
  bool success = 1;
  string message = 2;
  repeated float master_weights = 3;
}
